### ISSUE TITLE
coconut hangs in function "get_solver_env"

### ISSUE THREAD

**Issue by BastiLoe** [pyfsi/coconut#187]
I am running the Tube Example OpenFOAM 3D vs. Abaqus 3D. I modified solver_modules.py according to my environment (at least I think I did...).
While executing setup_case.py coconut hangs while executing "get_solver_env" for the CFD (openfoam) solver. By adding some statements I found out that the following code part in tools.py causes the system to hang:
`    try:
        subprocess.check_call(
            f'{solver_load_cmd} && python3 -c "from coconut import tools;tools.write_env()"',
            shell=True, cwd=working_dir, stdout=subprocess.DEVNULL, stderr=subprocess.DEVNULL)
    except subprocess.CalledProcessError:
        raise RuntimeError(f'Module load command for solver wrapper {solver_name} failed.')
`
For me the correct call of the python3 environment with all libraries available would be "python3.7" instead of just "python3". However, changing this part of the code did not change the behavior.

**Comment by BastiLoe** [comment]
After some investigation from my side: Our setup-script for OpenFOAM ended with the "bash" command which obviously opens a new shell. Removing that fixed this issue.
However, next one for Abaqus: I don't need a special command for this environment and created an empty sting as given in the documentation. This leads to the following:
`Traceback (most recent call last):
  File "/det07a/BL/coconut/tools.py", line 300, in get_solver_env
    shell=True, cwd=working_dir, stdout=subprocess.DEVNULL, stderr=subprocess.DEVNULL, timeout=10)
  File "/software20/anaconda3/lib/python3.7/subprocess.py", line 347, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command ' && python3 -c "from coconut import tools;tools.write_env()"' returned non-zero exit status 1.`
As a workaround just ANY valid command needs to be added in "solver_modules.py", e.g. as I did:
`'abaqus.v2019': 'echo "Abaqus.v2019"',`
